"""team_match_stats: source pasa a formar parte de la clave primaria

Revision ID: 5931be254a31
Revises: f4bfb4e8a46c
Create Date: 2026-08-28 10:16:10.085862

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5931be254a31"
down_revision: str | Sequence[str] | None = "f4bfb4e8a46c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate no detecta cambios de PRIMARY KEY: hay que
    # escribirlo a mano. 'source' entra a la clave para que FBref y Understat
    # puedan tener cada uno su propia fila para el mismo (fixture, equipo) en
    # vez de que la ultima fuente en escribir borre a la anterior.
    op.drop_constraint("team_match_stats_pkey", "team_match_stats", type_="primary")
    op.create_primary_key(
        "team_match_stats_pkey", "team_match_stats", ["fixture_id", "team_id", "source"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_match_stats",
        "source",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Adaptador que produjo la fila",
        existing_nullable=False,
    )
    op.alter_column(
        "team_match_stats",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Cuando se escribio la fila",
        existing_nullable=False,
    )
    op.create_table_comment(
        "team_match_stats",
        "Estadisticas por equipo, partido y fuente. 'source' es parte de la clave: FBref y Understat estiman xG por separado y ambas filas deben convivir en vez de que la ultima en llegar borre a la otra",
        existing_comment="Estadisticas por equipo y partido. Una fila por equipo",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "team_match_stats",
        "Estadisticas por equipo y partido. Una fila por equipo",
        existing_comment="Estadisticas por equipo, partido y fuente. 'source' es parte de la clave: FBref y Understat estiman xG por separado y ambas filas deben convivir en vez de que la ultima en llegar borre a la otra",
        schema=None,
    )
    op.alter_column(
        "team_match_stats",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Cuando se escribio la fila",
        existing_nullable=False,
    )
    op.alter_column(
        "team_match_stats",
        "source",
        existing_type=sa.VARCHAR(length=64),
        comment="Adaptador que produjo la fila",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    op.drop_constraint("team_match_stats_pkey", "team_match_stats", type_="primary")
    op.create_primary_key("team_match_stats_pkey", "team_match_stats", ["fixture_id", "team_id"])
