"""esquema inicial

Revision ID: b197a20b0418
Revises:
Create Date: 2026-08-28 02:20:52.473868

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b197a20b0418"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Catalogo de competiciones, espejo de config/competitions.yaml",
    )
    op.create_table(
        "model_registry",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("feature_set", sa.String(length=64), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("train_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("train_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "hyperparameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            comment="Brier, log loss y curva de fiabilidad por ventana",
        ),
        sa.Column("calibration_method", sa.String(length=32), nullable=True),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name", "model_version", name="uq_model_registry_natural"),
        comment="Una fila por version de modelo entrenada. Sin metricas no se despliega",
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "storage_path",
            sa.String(length=512),
            nullable=False,
            comment="Ruta relativa dentro de raw/",
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "endpoint", "content_hash", "fetched_at", name="uq_raw_documents_natural"
        ),
        comment="Capa cruda append-only. Se escribe la respuesta original ANTES de parsearla y no se sobrescribe nunca. Features y modelos deben poder reconstruirse desde aqui sin volver a raspar",
    )
    op.create_index(
        "ix_raw_source_fetched", "raw_documents", ["source", "fetched_at"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("canonical_name", sa.String(length=128), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Equipos canonicos. El nombre canonico es el de FBref cuando existe",
    )
    op.create_index("ix_teams_sport_name", "teams", ["sport", "canonical_name"], unique=False)
    op.create_table(
        "fixtures",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column(
            "season",
            sa.String(length=16),
            nullable=False,
            comment="Etiqueta de temporada, p.ej. '2425'",
        ),
        sa.Column(
            "kickoff_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Siempre UTC, nunca hora local",
        ),
        sa.Column("home_team_id", sa.String(length=96), nullable=False),
        sa.Column("away_team_id", sa.String(length=96), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True, comment="Fase, para copas"),
        sa.Column("matchday", sa.Integer(), nullable=True),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("home_score_ht", sa.Integer(), nullable=True),
        sa.Column("away_score_ht", sa.Integer(), nullable=True),
        sa.Column(
            "kickoff_is_estimated",
            sa.Boolean(),
            nullable=False,
            comment="La fuente no dio hora exacta",
        ),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "competition_id",
            "season",
            "home_team_id",
            "away_team_id",
            "kickoff_utc",
            name="uq_fixtures_natural",
        ),
        comment="Un partido. El id es un hash determinista de la clave natural",
    )
    op.create_index(
        "ix_fixtures_competition_kickoff",
        "fixtures",
        ["competition_id", "kickoff_utc"],
        unique=False,
    )
    op.create_index("ix_fixtures_kickoff", "fixtures", ["kickoff_utc"], unique=False)
    op.create_index("ix_fixtures_status", "fixtures", ["status"], unique=False)
    op.create_table(
        "team_aliases",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("alias", sa.String(length=128), nullable=False),
        sa.Column("team_id", sa.String(length=96), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("source", "sport", "alias"),
        comment="Reconciliacion de nombres entre fuentes. FBref, ESPN y football-data.co.uk escriben el mismo equipo de tres maneras distintas",
    )
    op.create_index("ix_team_aliases_team", "team_aliases", ["team_id"], unique=False)
    op.create_table(
        "features",
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("feature_set", sa.String(length=64), nullable=False, comment="Nombre y version"),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "vector",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("fixture_id", "feature_set"),
        comment="Vector de features de un partido. as_of_timestamp es el corte de informacion: nada en el vector puede conocerse despues de ese instante",
    )
    op.create_index(
        "ix_features_fixture_asof", "features", ["fixture_id", "as_of_timestamp"], unique=False
    )
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("bookmaker", sa.String(length=64), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("selection", sa.String(length=32), nullable=False),
        sa.Column(
            "line",
            sa.Float(precision=53),
            nullable=True,
            comment="Handicap o total; None si no aplica",
        ),
        sa.Column("price", sa.Float(precision=53), nullable=False, comment="Cuota decimal"),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Momento real de captura, no el programado",
        ),
        sa.Column(
            "is_closing", sa.Boolean(), nullable=False, comment="Ultima captura antes del kickoff"
        ),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id",
            "bookmaker",
            "market",
            "selection",
            "captured_at",
            name="uq_odds_snapshots_natural",
        ),
        comment="Cuota observada en un instante concreto. Sin captured_at una cuota no sirve: el backtest debe usar el precio disponible al decidir, no el cierre",
    )
    op.create_index("ix_odds_closing", "odds_snapshots", ["fixture_id", "is_closing"], unique=False)
    op.create_index(
        "ix_odds_fixture_captured", "odds_snapshots", ["fixture_id", "captured_at"], unique=False
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("selection", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Float(precision=53), nullable=True),
        sa.Column("prob_raw", sa.Float(precision=53), nullable=False),
        sa.Column(
            "prob_calibrated",
            sa.Float(precision=53),
            nullable=True,
            comment="None si el modelo no esta calibrado",
        ),
        sa.Column(
            "as_of_timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Corte de informacion de las features usadas",
        ),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id",
            "model_name",
            "model_version",
            "market",
            "selection",
            name="uq_predictions_natural",
        ),
        comment="Probabilidad cruda y calibrada por partido, mercado y seleccion",
    )
    op.create_index("ix_predictions_fixture", "predictions", ["fixture_id", "market"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("selection", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Float(precision=53), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column(
            "prob_model",
            sa.Float(precision=53),
            nullable=False,
            comment="Probabilidad calibrada del modelo",
        ),
        sa.Column(
            "prob_fair",
            sa.Float(precision=53),
            nullable=False,
            comment="Probabilidad justa del mercado, sin margen",
        ),
        sa.Column("fair_price", sa.Float(precision=53), nullable=False),
        sa.Column("entry_price", sa.Float(precision=53), nullable=False),
        sa.Column("entry_bookmaker", sa.String(length=64), nullable=False),
        sa.Column("entry_captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("devig_method", sa.String(length=32), nullable=False),
        sa.Column("edge", sa.Float(precision=53), nullable=False, comment="prob_model - prob_fair"),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column(
            "tier_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            comment="Que condicion de tier fallo o se cumplio",
        ),
        sa.Column(
            "stake_fraction",
            sa.Float(precision=53),
            nullable=False,
            comment="Fraccion del bankroll, Kelly fraccionado",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id",
            "market",
            "selection",
            "model_name",
            "model_version",
            name="uq_signals_natural",
        ),
        comment="Una apuesta senalada. tier='descartar' es una salida valida y se persiste: saber a que no apostar es parte del producto",
    )
    op.create_index("ix_signals_fixture_tier", "signals", ["fixture_id", "tier"], unique=False)
    op.create_table(
        "team_match_stats",
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("team_id", sa.String(length=96), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.Column("shots", sa.Integer(), nullable=True),
        sa.Column("shots_on_target", sa.Integer(), nullable=True),
        sa.Column("xg", sa.Float(precision=53), nullable=True),
        sa.Column("corners", sa.Integer(), nullable=True),
        sa.Column("yellow_cards", sa.Integer(), nullable=True),
        sa.Column("red_cards", sa.Integer(), nullable=True),
        sa.Column(
            "possession",
            sa.Float(precision=53),
            nullable=True,
            comment="Fraccion 0-1, no porcentaje",
        ),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("fixture_id", "team_id"),
        comment="Estadisticas por equipo y partido. Una fila por equipo",
    )
    op.create_table(
        "results",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column(
            "outcome",
            sa.String(length=16),
            nullable=False,
            comment="win/loss/push/half_win/half_loss/void",
        ),
        sa.Column(
            "pnl",
            sa.Float(precision=53),
            nullable=False,
            comment="En unidades de bankroll, neto del stake",
        ),
        sa.Column("closing_price", sa.Float(precision=53), nullable=True),
        sa.Column("closing_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "clv", sa.Float(precision=53), nullable=True, comment="entry_price/closing_price - 1"
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source", sa.String(length=64), nullable=False, comment="Adaptador que produjo la fila"
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Cuando se escribio la fila",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id", name="uq_results_natural"),
        comment="Liquidacion de una senal. El CLV es la metrica principal del sistema",
    )
    op.create_index("ix_results_fixture", "results", ["fixture_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_results_fixture", table_name="results")
    op.drop_table("results")
    op.drop_table("team_match_stats")
    op.drop_index("ix_signals_fixture_tier", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_predictions_fixture", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_odds_fixture_captured", table_name="odds_snapshots")
    op.drop_index("ix_odds_closing", table_name="odds_snapshots")
    op.drop_table("odds_snapshots")
    op.drop_index("ix_features_fixture_asof", table_name="features")
    op.drop_table("features")
    op.drop_index("ix_team_aliases_team", table_name="team_aliases")
    op.drop_table("team_aliases")
    op.drop_index("ix_fixtures_status", table_name="fixtures")
    op.drop_index("ix_fixtures_kickoff", table_name="fixtures")
    op.drop_index("ix_fixtures_competition_kickoff", table_name="fixtures")
    op.drop_table("fixtures")
    op.drop_index("ix_teams_sport_name", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_raw_source_fetched", table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_table("model_registry")
    op.drop_table("competitions")
    # ### end Alembic commands ###
