"""nfl_team_game_stats

Revision ID: da92247ec7a2
Revises: 5931be254a31
Create Date: 2026-08-29 01:53:12.141888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da92247ec7a2"
down_revision: str | Sequence[str] | None = "5931be254a31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nfl_team_game_stats",
        sa.Column("fixture_id", sa.String(length=64), nullable=False),
        sa.Column("team_id", sa.String(length=96), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("offensive_plays", sa.Integer(), nullable=False),
        sa.Column("offensive_epa_per_play", sa.Float(precision=53), nullable=True),
        sa.Column("offensive_success_rate", sa.Float(precision=53), nullable=True),
        sa.Column("defensive_plays", sa.Integer(), nullable=False),
        sa.Column("defensive_epa_per_play_allowed", sa.Float(precision=53), nullable=True),
        sa.Column("defensive_success_rate_allowed", sa.Float(precision=53), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["fixture_id"], ["fixtures.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("fixture_id", "team_id", "source"),
        comment=(
            "EPA/jugada y tasa de exito por equipo y partido de NFL, ofensiva y "
            "defensiva, agregadas desde play-by-play (nflfastR via nfl_data_py). "
            "'source' es parte de la clave por el mismo motivo que en team_match_stats"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nfl_team_game_stats")
    # ### end Alembic commands ###
