"""quitar unique constraint de tablas append-only

Revision ID: f4bfb4e8a46c
Revises: b197a20b0418
Create Date: 2026-08-28 02:56:24.214159

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4bfb4e8a46c"
down_revision: str | Sequence[str] | None = "b197a20b0418"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_model_registry_natural"), "model_registry", type_="unique")
    op.drop_constraint(op.f("uq_odds_snapshots_natural"), "odds_snapshots", type_="unique")
    op.drop_constraint(op.f("uq_raw_documents_natural"), "raw_documents", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_raw_documents_natural"),
        "raw_documents",
        ["source", "endpoint", "content_hash", "fetched_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_odds_snapshots_natural"),
        "odds_snapshots",
        ["fixture_id", "bookmaker", "market", "selection", "captured_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_model_registry_natural"),
        "model_registry",
        ["model_name", "model_version"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
