"""signals natural key pasa a ser id

Revision ID: fd1d285cdef7
Revises: 906fe3fef1a4
Create Date: 2026-08-30 05:03:47.041290

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd1d285cdef7"
down_revision: str | Sequence[str] | None = "906fe3fef1a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_COMMENT = (
    "Una apuesta senalada. tier='descartar' es una salida valida y se persiste: "
    "saber a que no apostar es parte del producto"
)
_NEW_COMMENT = (
    "Una apuesta senalada. tier='descartar' es una salida valida y se persiste: "
    "saber a que no apostar es parte del producto. 'id' es la clave natural real "
    "(no la tupla de columnas de negocio) por la misma razon que en predictions: "
    "'line' distingue senales del mismo mercado/seleccion y es nullable, asi que "
    "no puede ir en una clave natural — ver el docstring de modulo sobre ids "
    "surrogados"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_signals_natural"), "signals", type_="unique")
    op.create_table_comment("signals", _NEW_COMMENT, existing_comment=_OLD_COMMENT, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("signals", _OLD_COMMENT, existing_comment=_NEW_COMMENT, schema=None)
    op.create_unique_constraint(
        op.f("uq_signals_natural"),
        "signals",
        ["fixture_id", "market", "selection", "model_name", "model_version"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
